services:
  backend:
    container_name: fyp-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7146:7146"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=... ;Password=... ;etc.
    networks:
      - fyp-network

networks:
  fyp-network:
